AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - "node_modules/**/*"
    - "target/**/*"
    - "**/vendor/**/*"
Metrics:
  Enabled: false
Style/Documentation:
  Enabled: false
