---
name: Publish

"on":
  push:
    branches:
      - trunk

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment per branch
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    name: Build Site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "lts/*"

      - name: Install toolchain
        run: npm ci

      - name: Build Webapp
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist

  # Deployment job
  deploy:
    name: GitHub Pages deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
